# -*- coding: utf-8 -*-
"""Tarea_02

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GY-x8ZL9evHd2BWsCfQTNi4vV4MXg5sv

1. Hacer un programa que imprima los números del 1 al 100, en pyhton sería:
"""

print(range(100))

for x in range(100):
  print(x+1)

"""2. Hacer un programa que imprima los números del 1 al 100 que sean divisibles entre 3 (con resto 0)"""

for x in range(100):

  if (x+1) % 3 == 0:
    print(x+1)

"""3. Pseudocódigo, Sumador y comparador de dos números: realiza el algoritmo para un sumador de dos números. Si el resultado es mneor a 100 se mostrará el mensaje "menos a 100", si el resultado es mayor a 100, pero mneor a 150 mostrará el mensaje "mayor a 100", pero si es mayor a 150 mostrará el mensjae "mayor a 150"."""

numero_1 = int(input("Ingresa un número"))
numero_2 = 5
suma = numero_1 + numero_2
resultado = ""

if(suma<100):
  resultado = "menor a 100"
elif(suma>=100 and suma<150):
  resultado = "mayor a 100"
elif(suma>=150):
  resultado = "mayor a 150"

print(resultado)

"""4. Generar un programa que combine variables, tipos de datos y una condicional en Python (hacer una función que evalúe si el usuario es mayor de edad y si le gusta la programación, que envíe diferentes textos según la respuesta del usuario)."""

edad = int(input("¿Cuál es tu edad? "))

gusta_programar = input("¿Te gusta la programación? (Sí/No) ")
#acá se definieron las dos variables que van a ser preguntadas

if edad >= 18 and gusta_programar == "sí":
    print("Eres mayor de edad y te gusta la programación.")
elif edad >= 18 and gusta_programar == "no":
    print("Eres mayor de edad y no te gusta la programación.")
elif edad < 18 and gusta_programar == "sí":
    print("No eres mayor de edad y te gusta la programación.")
else:
    print("No eres mayor de edad y no te gusta la programación.")

#acá se definió que tipos de datos se van a preguntas (números en edad y si/no)
#además se definió las condicionales con los elif y con el else
#también se definió que textos van a salir dependiendo la respuesta en ambas variables